### ISSUE TITLE
Documentary

### ISSUE THREAD

**Issue by JonasNapierski** [zirkumflexlab/Rabbit2MySQL#1]
# Todo
- [ ] Code Documentation
- [ ] Repo Documentation (Create a proper. Readme)
- [ ] Documrntation on how to use
- [ ] how to Debug
